// src/context/LanguageContext.tsx
import { createContext, useState } from 'react';
import type { ReactNode } from 'react';

export type Language = 'en' | 'af' | 'zu' | 'xh' | 'st' | 'tn' | 'nso' | 'ts' | 've' | 'ss' | 'nr';
interface Translations {
    home: string;
    findTutor: string;
    resources: string;
    dashboard: string;
    logout: string;
    signUp: string;
    logIn: string;
    selectRole: string;
    learner: string;
    tutor: string;
    email: string;
    password: string;
    loginBtn: string;
    noAccount: string;
    createAccount: string;
    chooseRole: string;
    iAmLearner: string;
    iAmTutor: string;
    fullName: string;
    createPassword: string;
    currentGrade: string;
    selectGrade: string;
    grade10: string;
    grade11: string;
    grade12: string;
    province: string;
    selectProvince: string;
    subjectsTeach: string;
    yearsExp: string;
    signUpLearner: string;
    signUpTutor: string;
    alreadyAccount: string;
    unlockTitle: string;
    unlockSubtitle: string;
    joinWaitlist: string;
    exploreSubjects: string;
    beFirst: string;
    joinDescription: string;
    enterEmail: string;
    thankYou: string;
    subjectsMatter: string;
    subjectsSubtitle: string;
    whatBuilding: string;
    gatewayMastery: string;
    gatewayMasteryDesc: string;
    affordableDesign: string;
    affordableDesignDesc: string;
    dataLight: string;
    dataLightDesc: string;
    findTutorTitle: string;
    searchSubject: string;
    allProvinces: string;
    requestSession: string;
    preferredDate: string;
    preferredTime: string;
    helpWith: string;
    confirmRequest: string;
    cancel: string;
    requestSent: string;
    requestSentDesc: string;
    close: string;
    noTutorsFound: string;
    resourcesTitle: string;
    resourcesSubtitle: string;
    downloadPDF: string;
    officialSource: string;
    hi: string;
    mySessions: string;
    noSessionsBooked: string;
    findTutorBtn: string;
    subjectProgress: string;
    progressDesc: string;
    tutorLabel: string;
    dateLabel: string;
    messageLabel: string;
    statusLabel: string;
    waitingTutor: string;
    accepted: string;
    declined: string;
    chatWhatsApp: string;
    joinMeeting: string;
    howItWorks: string;
    howStep1Title: string;
    howStep1Desc: string;
    howStep2Title: string;
    howStep2Desc: string;
    howStep3Title: string;
    howStep3Desc: string;
}

const translations: Record<Language, Translations> = {
    en: {
        home: 'Home',
        findTutor: 'Find a Tutor',
        resources: 'Resources',
        dashboard: 'My Dashboard',
        logout: 'Log Out',
        signUp: 'Sign Up',
        logIn: 'Log In',
        selectRole: 'Select your role to continue.',
        learner: 'Learner',
        tutor: 'Tutor',
        email: 'Email Address',
        password: 'Password',
        loginBtn: 'Log In',
        noAccount: "Don't have an account?",
        createAccount: 'Create your account',
        chooseRole: 'Choose your role to get started.',
        iAmLearner: 'I am a Learner',
        iAmTutor: 'I am a Tutor',
        fullName: 'Full Name',
        createPassword: 'Create a password',
        currentGrade: 'Current Grade',
        selectGrade: 'Select Grade',
        grade10: 'Grade 10',
        grade11: 'Grade 11',
        grade12: 'Grade 12 (Matric)',
        province: 'Province',
        selectProvince: 'Select Province',
        subjectsTeach: 'Subjects you can teach',
        yearsExp: 'Years of Experience',
        signUpLearner: 'Sign Up as Learner',
        signUpTutor: 'Sign Up as Tutor',
        alreadyAccount: 'Already have an account?',
        unlockTitle: 'Unlock Your University Entrance.',
        unlockSubtitle: 'Over 700,000 students qualified for tertiary study last year, but hundreds of thousands were turned away. We are building an affordable, localized platform to help you ace the critical gateway subjects.',
        joinWaitlist: 'Join the Waitlist',
        exploreSubjects: 'Explore Subjects',
        beFirst: 'Be the first to know.',
        joinDescription: 'Join our waitlist to get early access when we launch.',
        enterEmail: 'Enter your email address',
        thankYou: "You're on the list!",
        subjectsMatter: 'The Subjects That Matter',
        subjectsSubtitle: 'Mastering these opens the doors to Engineering, Medicine, Commerce, and Law.',
        whatBuilding: 'What we are building for you',
        gatewayMastery: 'Gateway Subject Mastery',
        gatewayMasteryDesc: 'Focused tools for the subjects that gatekeep university entrance.',
        affordableDesign: 'Affordable by Design',
        affordableDesignDesc: 'Cutting out the R300+/hour overhead to make quality academic support accessible.',
        dataLight: 'Data-Light & Local',
        dataLightDesc: 'Built for South Africa. Low data usage, mobile-first, and support for 11 languages.',
        findTutorTitle: 'Find Your Tutor',
        searchSubject: 'Search by subject (e.g. Pure Maths)',
        allProvinces: 'All Provinces',
        requestSession: 'Request Session',
        preferredDate: 'Preferred Date',
        preferredTime: 'Preferred Time',
        helpWith: 'What do you need help with?',
        confirmRequest: 'Confirm Request',
        cancel: 'Cancel',
        requestSent: 'Request Sent!',
        requestSentDesc: 'Your session request has been sent successfully.',
        close: 'Close',
        noTutorsFound: 'No tutors found for your search. Try another subject or province.',
        resourcesTitle: 'Data-Light Learning Library',
        resourcesSubtitle: 'Browse official past papers and summaries from the DBE and WCED.',
        downloadPDF: 'Download PDF (Uses Data)',
        officialSource: 'Official Source',
        hi: 'Hi',
        mySessions: 'My Sessions',
        noSessionsBooked: 'No sessions booked yet. Book a tutor to get started!',
        findTutorBtn: 'Find a Tutor',
        subjectProgress: 'Subject Progress',
        progressDesc: 'Track your progress here once you start sessions.',
        tutorLabel: 'Tutor',
        dateLabel: 'Date',
        messageLabel: 'Message',
        statusLabel: 'Status',
        waitingTutor: 'Waiting for Tutor',
        accepted: 'Accepted',
        declined: 'Declined',
        chatWhatsApp: 'Chat on WhatsApp',
        joinMeeting: 'Join Meeting',
        howItWorks: 'How It Works',
        howStep1Title: 'Sign Up',
        howStep1Desc: 'Create your free account as a Learner or a Tutor in under 2 minutes.',
        howStep2Title: 'Find a Match',
        howStep2Desc: 'Browse verified tutors by subject and province, check their reviews, and chat on WhatsApp.',
        howStep3Title: 'Book & Learn',
        howStep3Desc: 'Request a session, get accepted, and meet online via Zoom, Teams, or Jitsi.',
    },
    af: {
        home: 'Tuis',
        findTutor: 'Vind `n Tutor',
        resources: 'Hulpbronne',
        dashboard: 'My Dashboard',
        logout: 'Teken Uit',
        signUp: 'Teken Aan',
        logIn: 'Meld Aan',
        selectRole: 'Kies jou rol om voort te gaan.',
        learner: 'Leerder',
        tutor: 'Tutor',
        email: 'E-posadres',
        password: 'Wagwoord',
        loginBtn: 'Meld Aan',
        noAccount: "Het jy nie `n rekening nie?",
        createAccount: 'Skep jou rekening',
        chooseRole: 'Kies jou rol om te begin.',
        iAmLearner: 'Ek is `n Leerder',
        iAmTutor: 'Ek is `n Tutor',
        fullName: 'Volle Naam',
        createPassword: 'Skep `n wagwoord',
        currentGrade: 'Huidige Graad',
        selectGrade: 'Kies Graad',
        grade10: 'Graad 10',
        grade11: 'Graad 11',
        grade12: 'Graad 12 (Matriek)',
        province: 'Provinsie',
        selectProvince: 'Kies Provinsie',
        subjectsTeach: 'Vakke wat jy kan onderrig',
        yearsExp: 'Jare Ondervinding',
        signUpLearner: 'Teken aan as Leerder',
        signUpTutor: 'Teken aan as Tutor',
        alreadyAccount: 'Reeds `n rekening?',
        unlockTitle: 'Ontgrendel jou Universiteitstoelating.',
        unlockSubtitle: 'Meer as 700,000 studente het verlede jaar vir tersiêre studie gekwalifiseer, maar honderde duisende is van die hand gewys. Ons bou `n bekostigbare, gelokaliseerde platform om jou te help om die kritieke onderwerpe te bemeester.',
        joinWaitlist: 'Sluit by die Waglys aan',
        exploreSubjects: 'Verken Onderwerpe',
        beFirst: 'Wees die eerste om te weet.',
        joinDescription: 'Sluit by ons waglys aan om vroeë toegang te kry wanneer ons bekendstel.',
        enterEmail: 'Voer jou e-posadres in',
        thankYou: "Jy is op die lys!",
        subjectsMatter: 'Die Onderwerpe wat Saak Maak',
        subjectsSubtitle: 'Om hierdie te bemeester open die deure na Ingenieurswese, Geneeskunde, Handel en Regte.',
        whatBuilding: 'Wat ons vir jou bou',
        gatewayMastery: 'Poort Onderwerp Meesterskap',
        gatewayMasteryDesc: 'Gefokusde gereedskap vir die onderwerpe wat universiteitstoelating beheer.',
        affordableDesign: 'Bekostigbaar deur Ontwerp',
        affordableDesignDesc: 'Sny die R300+/uur oorhoofse koste om kwaliteit akademiese ondersteuning toeganklik te maak.',
        dataLight: 'Data-Lig & Plaaslik',
        dataLightDesc: 'Gebou vir Suid-Afrika. Lae dataverbruik, mobiel-eerste, en ondersteuning vir 11 tale.',
        findTutorTitle: 'Vind Jou Tutor',
        searchSubject: 'Soek per vak (bv. Wiskunde)',
        allProvinces: 'Alle Provinsies',
        requestSession: 'Versoek Sessie',
        preferredDate: 'Voorkeur Datum',
        preferredTime: 'Voorkeur Tyd',
        helpWith: 'Waarmee benodig jy hulp?',
        confirmRequest: 'Bevestig Versoek',
        cancel: 'Kanselleer',
        requestSent: 'Versoek Gestuur!',
        requestSentDesc: 'Jou sessieversoek is suksesvol gestuur.',
        close: 'Maak toe',
        noTutorsFound: 'Geen tutors gevind vir jou soektog nie. Probeer `n ander vak of provinsie.',
        resourcesTitle: 'Data-Lig Leerbiblioteek',
        resourcesSubtitle: 'Blaai deur amptelike vorige vraestelle en opsommings van die DBE en WCED.',
        downloadPDF: 'Laai PDF Af (Gebruik Data)',
        officialSource: 'Amptelike Bron',
        hi: 'Hallo',
        mySessions: 'My Sessies',
        noSessionsBooked: 'Geen sessies bespreek nie. Bespreek `n tutor om te begin!',
        findTutorBtn: 'Vind `n Tutor',
        subjectProgress: 'Vak Vordering',
        progressDesc: 'Volg jou vordering hier sodra jy met sessies begin.',
        tutorLabel: 'Tutor',
        dateLabel: 'Datum',
        messageLabel: 'Boodskap',
        statusLabel: 'Status',
        waitingTutor: 'Wag vir Tutor',
        accepted: 'Aanvaar',
        declined: 'Geweier',
        chatWhatsApp: 'Gesels op WhatsApp',
        joinMeeting: 'Sluit aan by Vergadering',
        howItWorks: 'Hoe Dit Werk',
        howStep1Title: 'Teken Aan',
        howStep1Desc: 'Skep jou gratis rekening as `n Leerder of `n Tutor in minder as 2 minute.',
        howStep2Title: 'Vind `n Wedstryd',
        howStep2Desc: 'Blaai deur geverifieerde tutors per vak en provinsie, kyk na hul resensies, en gesels op WhatsApp.',
        howStep3Title: 'Bespreek & Leer',
        howStep3Desc: 'Versoek `n sessie, word aanvaar, en ontmoet aanlyn via Zoom, Teams, of Jitsi.',
    },
    zu: {
        home: 'Ikhaya',
        findTutor: 'Thola Umfundisi',
        resources: 'Izinsiza',
        dashboard: 'I-Dashboard Yami',
        logout: 'Phuma',
        signUp: 'Bhalisa',
        logIn: 'Ngena',
        selectRole: 'Khetha indima yakho ukuze uqhubeke.',
        learner: 'Umfundi',
        tutor: 'Umfundisi',
        email: 'Ikheli le-imeyili',
        password: 'Iphasiwedi',
        loginBtn: 'Ngena',
        noAccount: 'Awenayo i-akhawunti?',
        createAccount: 'Dala i-akhawunti yakho',
        chooseRole: 'Khetha indima yakho ukuze uqale.',
        iAmLearner: 'Ngiy Umfundi',
        iAmTutor: 'Ngiy Umfundisi',
        fullName: 'Igama Eliphelele',
        createPassword: 'Dala iphasiwedi',
        currentGrade: 'Ibanga Lamanje',
        selectGrade: 'Khetha Ibanga',
        grade10: 'Ibanga 10',
        grade11: 'Ibanga 11',
        grade12: 'Ibanga 12 (Matric)',
        province: 'Isifundazwe',
        selectProvince: 'Khetha Isifundazwe',
        subjectsTeach: 'Izifundo ozifundisayo',
        yearsExp: 'Iminyaka Yesipiliyoni',
        signUpLearner: 'Bhalisa njengo Mfundi',
        signUpTutor: 'Bhalisa njengo Mfundisi',
        alreadyAccount: 'Usuvele une-akhawunti?',
        unlockTitle: 'Vula Ukungena Kwakho Eyunivesithi.',
        unlockSubtitle: 'Bafundi abangaphezu kuka-700,000 bafanelekele izifundo zemfundo ephakeme nyakenye, kodwa amakhulu ezinkulungwane acishwa.',
        joinWaitlist: 'Joyina Uhlu Lokulinda',
        exploreSubjects: 'Hlola Izifundo',
        beFirst: 'Yiba ngowokuqala ukwazi.',
        joinDescription: 'Joyina uhlu lwethu lokulinda ukuze uthole ukufinyelela kwangaphambi kokuthi sisungule.',
        enterEmail: 'Faka ikheli lakho le-imeyili',
        thankYou: "Usoluhlu!",
        subjectsMatter: 'Izifundo Ezibalulekile',
        subjectsSubtitle: 'Ukuqonda lezi kuvula iminyango yezobunjiniyela, ezokwelapha, ezebhizinisi, nezomthetho.',
        whatBuilding: 'Okukwakhela wena',
        gatewayMastery: 'Ukugcizelela Izifundo Ezibalulekile',
        gatewayMasteryDesc: 'Amathuluzi agxile ezifundweni ezivula amasango eyunivesithi.',
        affordableDesign: 'Kuyafinyeleleka Ngokwakhiwa',
        affordableDesignDesc: 'Ukunciphisa izindleko eziphakeme zama-R300+/ihora ukuze kufinyeleleke kusizo lwezemfundo olusezingeni eliphezulu.',
        dataLight: 'Kuncane Idatha & Yasendaweni',
        dataLightDesc: 'Yakhelwe iNingizimu Afrika. Ukusetshenziswa kwedatha okuphansi, okokuqala imobile, nokusekela izilimi eziyi-11.',
        findTutorTitle: 'Thola Umfundisi Wakho',
        searchSubject: 'Sesha ngesifundo (isb. Izibalo)',
        allProvinces: 'Zonke Izifundazwe',
        requestSession: 'Cela Iseshini',
        preferredDate: 'Usuku Olikhethayo',
        preferredTime: 'Isikhathi Okhetha Sonke',
        helpWith: 'Yini odinga usizo ngayo?',
        confirmRequest: 'Qinisekisa Isicelo',
        cancel: 'Khansela',
        requestSent: 'Isicelo Sithunyelwe!',
        requestSentDesc: 'Isicelo sakho seseshini sithunyelwe ngempumelelo.',
        close: 'Vala',
        noTutorsFound: 'Abafundisi abatholakalanga okuseshayo. Zama esinye isifundo noma isifundazwe.',
        resourcesTitle: 'Umtapo Wolwazi Wokufunda Oncane',
        resourcesSubtitle: 'Browza amaphepha wokuhlola asemthethweni nezifinyezo ezivela ku-DBE ne-WCED.',
        downloadPDF: 'Landa i-PDF (Kusetshenziswa Idatha)',
        officialSource: 'Umthombo Osemthethweni',
        hi: 'Sawubona',
        mySessions: 'Izikhathi Zami Zokufunda',
        noSessionsBooked: 'Azikho izikhathi zokufunda ozibhukile. Bhuka umfundisi ukuze uqale!',
        findTutorBtn: 'Thola Umfundisi',
        subjectProgress: 'Intuthuko Yezifundo',
        progressDesc: 'Landelela intuthuko yakho lapha uma uqala izikhathi zokufunda.',
        tutorLabel: 'Umfundisi',
        dateLabel: 'Usuku',
        messageLabel: 'Umlayezo',
        statusLabel: 'Isimo',
        waitingTutor: 'Ulinde Umfundisi',
        accepted: 'Yamukelwe',
        declined: 'Yenqatshwa',
        chatWhatsApp: 'Xhumana nge-WhatsApp',
        joinMeeting: 'Joyina Umhlangano',
        howItWorks: 'Isebenza Kanjani',
        howStep1Title: 'Bhalisa',
        howStep1Desc: 'Dala i-akhawunti yakho yamahhala njengo Mfundi noma uMfundisi ngaphansi kwemizuzu emi-2.',
        howStep2Title: 'Thola Umfundisi',
        howStep2Desc: 'Browza abafundisi abaqinisekisiwe ngesifundo nesifundazwe, bheka izibuyekezo zabo, futhi uxoxe ku-WhatsApp.',
        howStep3Title: 'Bhuka & Funda',
        howStep3Desc: 'Cela iseshini, yamukelwe, futhi uhlangane ku-inthanethi nge-Zoom, Teams, noma i-Jitsi.',
    },
    xh: {
        home: 'Ekhaya',
        findTutor: 'Fumana Umfundisi',
        resources: 'Izixhobo',
        dashboard: 'Idashboard Yam',
        logout: 'Phuma',
        signUp: 'Bhalisa',
        logIn: 'Ngena',
        selectRole: 'Khetha indima yakho ukuze uqhubeke.',
        learner: 'Umfundi',
        tutor: 'Umfundisi',
        email: 'Idilesi ye-imeyile',
        password: 'Igama lokugqitha',
        loginBtn: 'Ngena',
        noAccount: 'Awunayo i-akhawunti?',
        createAccount: 'Yenza i-akhawunti yakho',
        chooseRole: 'Khetha indima yakho ukuze uqale.',
        iAmLearner: 'NdinguMfundi',
        iAmTutor: 'NdinguMfundisi',
        fullName: 'Igama Elipheleleyo',
        createPassword: 'Yenza igama lokugqitha',
        currentGrade: 'Ibanga Langoku',
        selectGrade: 'Khetha Ibanga',
        grade10: 'Ibanga 10',
        grade11: 'Ibanga 11',
        grade12: 'Ibanga 12 (Matric)',
        province: 'Iphondo',
        selectProvince: 'Khetha Iphondo',
        subjectsTeach: 'Izifundo onokuzifundisa',
        yearsExp: 'Iminyaka Yamava',
        signUpLearner: 'Bhalisa njengoMfundi',
        signUpTutor: 'Bhalisa njengoMfundisi',
        alreadyAccount: 'Sele unayo i-akhawunti?',
        unlockTitle: 'Vula Ukungena Kwakho Eyunivesithi.',
        unlockSubtitle: 'Abafundi abangaphezulu kwe-700,000 bafanelekela izifundo zemfundo ephakamileyo kunyaka ophelileyo, kodwa amakhulu amawaka akhutshwa.',
        joinWaitlist: 'Joyina Uluhlu Lokulinda',
        exploreSubjects: 'Hlola Izifundo',
        beFirst: 'Yiba ngowokuqala ukwazi.',
        joinDescription: 'Joyina uluhlu lwethu lokulinda ukuze ufumane ukufikelela kwangaphambili xa siqala.',
        enterEmail: 'Faka idilesi yakho ye-imeyile',
        thankYou: "Usoluhlu!",
        subjectsMatter: 'Izifundo Ezibalulekileyo',
        subjectsSubtitle: 'Ukuqonda ezi zivula iingcango zobuNjineli, ezonyango, ezorhwebo, nezomthetho.',
        whatBuilding: 'Oko sikwakhela kona',
        gatewayMastery: 'Ukugxila Kwizifundo Ezibalulekileyo',
        gatewayMasteryDesc: 'Izixhobo ezigxile kwizifundo ezivula amasango eyunivesithi.',
        affordableDesign: 'Iyafikeleleka Ngoyilo',
        affordableDesignDesc: 'Ukunciphisa iindleko eziphezulu zama-R300+/iyure ukuze kufikeleleke kuncedo lwezemfundo olusemgangathweni.',
        dataLight: 'Incinci Idatha & Yasekhaya',
        dataLightDesc: 'Yakhelwe uMzantsi Afrika. Ukusetyenziswa kwedatha okuphantsi, kuqala imobile, kunye nenkxaso kwiilwimi ezili-11.',
        findTutorTitle: 'Fumana Umfundisi Wakho',
        searchSubject: 'Khangela ngesifundo (umz. IZibalo)',
        allProvinces: 'Onke AmaPhondo',
        requestSession: 'Cela Iseshini',
        preferredDate: 'Umhla Owukhethayo',
        preferredTime: 'Ixesha Olikhethayo',
        helpWith: 'Yintoni ofuna uncedo ngayo?',
        confirmRequest: 'Qinisekisa Isicelo',
        cancel: 'Rhoxisa',
        requestSent: 'Isicelo Sithunyelwe!',
        requestSentDesc: 'Isicelo sakho seseshini sithunyelwe ngempumelelo.',
        close: 'Vala',
        noTutorsFound: 'Akukho bafundisi bafunyenweyo kukhangelo lwakho. Zama esinye isifundo okanye iphondo.',
        resourcesTitle: 'Ithala Lokufunda Elincinci',
        resourcesSubtitle: 'Khangela amaphepha ovavanyo asemthethweni kunye nezishwankathelo ezivela kwi-DBE ne-WCED.',
        downloadPDF: 'Khuphela i-PDF (Kusetyenziswa Idatha)',
        officialSource: 'Umthombo Osemthethweni',
        hi: 'Molo',
        mySessions: 'Iiseshini Zam',
        noSessionsBooked: 'Akukho seshini zibhukiweyo. Bhuka umfundisi ukuze uqale!',
        findTutorBtn: 'Fumana Umfundisi',
        subjectProgress: 'Inkqubela Yesifundo',
        progressDesc: 'Landela inkqubela yakho apha xa uqala iiseshini.',
        tutorLabel: 'Umfundisi',
        dateLabel: 'Umhla',
        messageLabel: 'Umyalezo',
        statusLabel: 'Imeko',
        waitingTutor: 'Ulinde Umfundisi',
        accepted: 'Yamkelwe',
        declined: 'Yaliwe',
        chatWhatsApp: 'Ncokola nge-WhatsApp',
        joinMeeting: 'Joyina Intlanganiso',
        howItWorks: 'Isebenza Njani',
        howStep1Title: 'Bhalisa',
        howStep1Desc: 'Yenza i-akhawunti yakho yasimahla njengoMfundi okanye uMfundisi ngaphantsi kwemizuzu emi-2.',
        howStep2Title: 'Fumana Umfundisi',
        howStep2Desc: 'Khangela abafundisi abaqinisekisiweyo ngesifundo nangephondo, jonga izimvo zabo, kwaye uncokole nge-WhatsApp.',
        howStep3Title: 'Bhuka & Funda',
        howStep3Desc: 'Cela iseshini, yamkelwe, kwaye udibane kwi-intanethi nge-Zoom, Teams, okanye i-Jitsi.',
    },
    st: {
        home: 'Lehae',
        findTutor: 'Fumana Morupelli',
        resources: 'Lisebelisoa',
        dashboard: 'Dashboard ya Ka',
        logout: 'Tsoa',
        signUp: 'Ingolisa',
        logIn: 'Kena',
        selectRole: 'Khetha karolo ea hau ho tsoela pele.',
        learner: 'Moithuti',
        tutor: 'Morupelli',
        email: 'Aterese ea imeile',
        password: 'Phasewete',
        loginBtn: 'Kena',
        noAccount: 'Ha u na akhaonto?',
        createAccount: 'Theha akhaonto ea hau',
        chooseRole: 'Khetha karolo ea hau ho qala.',
        iAmLearner: 'Ke Moithuti',
        iAmTutor: 'Ke Morupelli',
        fullName: 'Lebitso le Feletseng',
        createPassword: 'Theha phasewete',
        currentGrade: 'Kereiti ea Hona Joale',
        selectGrade: 'Khetha Kereiti',
        grade10: 'Kereiti 10',
        grade11: 'Kereiti 11',
        grade12: 'Kereiti 12 (Matric)',
        province: 'Profense',
        selectProvince: 'Khetha Profense',
        subjectsTeach: 'Lithuto tseo u ka li rupelang',
        yearsExp: 'Lilemo tsa Boiphihlelo',
        signUpLearner: 'Ingolisa joalo ka Moithuti',
        signUpTutor: 'Ingolisa joalo ka Morupelli',
        alreadyAccount: 'U se u na le akhaonto?',
        unlockTitle: 'Bula Monyako oa Hau oa Yunivesithi.',
        unlockSubtitle: 'Baithuti ba fetang 700,000 ba ile ba tšoaneleha bakeng sa thuto e phahameng selemong se fetileng, empa likete tsa ba neng ba le teng li ile tsa haneloa.',
        joinWaitlist: 'Kenela Lenane la ho Emela',
        exploreSubjects: 'Hlahloba Lithuto',
        beFirst: 'E-ba oa pele ho tseba.',
        joinDescription: 'Kenela lenane la rona la ho emela ho fumana phihlello ea pele ha re qala.',
        enterEmail: 'Kenya aterese ea hau ea imeile',
        thankYou: "U lenaneng!",
        subjectsMatter: 'Lithuto tse Bohlokoa',
        subjectsSubtitle: 'Ho tseba tsena ho bula menyako ea Boenjiniere, Bongaka, Khoebo le Molao.',
        whatBuilding: 'Seo re u ahelang sona',
        gatewayMastery: 'Ho Tseba Lithuto tsa Bohlokoa',
        gatewayMasteryDesc: 'Lisebelisoa tse lebisitsoeng ho lithuto tse thibang monyako oa yunivesithi.',
        affordableDesign: 'E Fumaneha ka Theko e Tlase',
        affordableDesignDesc: 'Ho fokotsa litšenyehelo tse phahameng tsa R300+/hora ho etsa hore tšehetso ea thuto e fumanehe.',
        dataLight: 'Data e Nyane & Ea Lehae',
        dataLightDesc: 'E hahetse Afrika Boroa. Tšebeliso e tlase ea data, mobile pele, le tšehetso ea lipuo tse 11.',
        findTutorTitle: 'Fumana Morupelli oa Hau',
        searchSubject: 'Batla ka thuto (mohl. Lipalo)',
        allProvinces: 'Liprofense Tsohle',
        requestSession: 'Kopa Seshene',
        preferredDate: 'Letsatsi leo u le Ratang',
        preferredTime: 'Nako eo u e Ratang',
        helpWith: 'U hloka thuso ka eng?',
        confirmRequest: 'Netefatsa Kopo',
        cancel: 'Hlakola',
        requestSent: 'Kopo e Romelitsoe!',
        requestSentDesc: 'Kopo ea hau ea seshene e rometsoe ka katleho.',
        close: 'Koala',
        noTutorsFound: 'Ha ho barupelli ba fumanoeng bakeng sa patlisiso ea hau. Leka thuto kapa profense e ngoe.',
        resourcesTitle: 'Laebrari ea ho Ithuta ea Data e Nyane',
        resourcesSubtitle: 'Sheba lipampiri tsa tlhahlobo tsa semmuso le likakaretso tse tsoang ho DBE le WCED.',
        downloadPDF: 'Khoasolla PDF (Ho Sebelisa Data)',
        officialSource: 'Mohloli oa Semmuso',
        hi: 'Lumela',
        mySessions: 'Liseshini tsa Ka',
        noSessionsBooked: 'Ha ho liseshini tse behiloeng. Beha morupelli ho qala!',
        findTutorBtn: 'Fumana Morupelli',
        subjectProgress: 'Tsoelo-pele ea Thuto',
        progressDesc: 'Latela tsoelo-pele ea hau mona ha u qala liseshini.',
        tutorLabel: 'Morupelli',
        dateLabel: 'Letsatsi',
        messageLabel: 'Molaetsa',
        statusLabel: 'Boemo',
        waitingTutor: 'E emetse Morupelli',
        accepted: 'E Amohetsoe',
        declined: 'E Hanoe',
        chatWhatsApp: 'Buisana ka WhatsApp',
        joinMeeting: 'Kenela Kopano',
        howItWorks: 'E Sebetsa Joang',
        howStep1Title: 'Ingolisa',
        howStep1Desc: 'Theha akhaonto ea hau ea mahala joalo ka Moithuti kapa Morupelli ka tlase ho metsotso e 2.',
        howStep2Title: 'Fumana Morupelli',
        howStep2Desc: 'Sheba barupelli ba netefalitsoeng ka thuto le profense, sheba maikutlo a bona, mme u buisane ka WhatsApp.',
        howStep3Title: 'Beha & Ithuta',
        howStep3Desc: 'Kopa seshene, e amoheloe, mme u kopane inthaneteng ka Zoom, Teams, kapa Jitsi.',
    },
    tn: {
        home: 'Gae',
        findTutor: 'Batla Morutabana',
        resources: 'Dithusa',
        dashboard: 'Dashboard ya Me',
        logout: 'Tswa',
        signUp: 'Ikwadise',
        logIn: 'Tsena',
        selectRole: 'Tlhopha karolo ya gago go tswelela.',
        learner: 'Moithuti',
        tutor: 'Morutabana',
        email: 'Aterese ya imeile',
        password: 'Phasewete',
        loginBtn: 'Tsena',
        noAccount: 'Ga o na akhaonto?',
        createAccount: 'Dira akhaonto ya gago',
        chooseRole: 'Tlhopha karolo ya gago go simolola.',
        iAmLearner: 'Ke Moithuti',
        iAmTutor: 'Ke Morutabana',
        fullName: 'Leina le Feletseng',
        createPassword: 'Dira phasewete',
        currentGrade: 'Mophato wa Jaanong',
        selectGrade: 'Tlhopha Mophato',
        grade10: 'Mophato 10',
        grade11: 'Mophato 11',
        grade12: 'Mophato 12 (Matric)',
        province: 'Porofense',
        selectProvince: 'Tlhopha Porofense',
        subjectsTeach: 'Dithuto tse o ka di rutang',
        yearsExp: 'Dingwaga tsa Boitseanape',
        signUpLearner: 'Ikwadise jaaka Moithuti',
        signUpTutor: 'Ikwadise jaaka Morutabana',
        alreadyAccount: 'O setse o na le akhaonto?',
        unlockTitle: 'Bula Tsela ya Gago ya Yunibesiti.',
        unlockSubtitle: 'Baithuti ba ba fetang 700,000 ba ne ba tshwanelega go ithuta kwa yunibesithing ngogola, mme dikete tsa batho ba ne ba ganelwa.',
        joinWaitlist: 'Tsenela Lenane la go Leta',
        exploreSubjects: 'Sekaseka Dithuto',
        beFirst: 'Nna wa ntlha go itse.',
        joinDescription: 'Tsenela lenane la rona la go leta go bona phitlhelelo ya pele fa re simolola.',
        enterEmail: 'Tsenya aterese ya gago ya imeile',
        thankYou: "O mo lenaneng!",
        subjectsMatter: 'Dithuto tse di Botlhokwa',
        subjectsSubtitle: 'Go itse tse di bulela dikgoro tsa Boenjiniri, Bongaka, Kgwebo le Molao.',
        whatBuilding: 'Se re go agelang sona',
        gatewayMastery: 'Go Itse Dithuto tsa Botlhokwa',
        gatewayMasteryDesc: 'Didirisiwa tse di tlhophilweng mo dithutong tse di thibang kgoro ya yunibesithi.',
        affordableDesign: 'E Bonolo ka Theko',
        affordableDesignDesc: 'Go fokotsa ditshenyegelo tse di kwa godimo tsa R300+/ura go dira gore thuso ya thuto e bonale.',
        dataLight: 'Data e Nnye & ya Legae',
        dataLightDesc: 'E agetswe Aforika Borwa. Tiriso e nnye ya data, mobile pele, le tshegetso ya dipuo tse 11.',
        findTutorTitle: 'Batla Morutabana wa Gago',
        searchSubject: 'Batla ka thuto (sk. Dipalo)',
        allProvinces: 'Diproforense Tsotlhe',
        requestSession: 'Kopa Seshene',
        preferredDate: 'Letlha le o le Ratang',
        preferredTime: 'Nako e o e Ratang',
        helpWith: 'O tlhoka thuso ka eng?',
        confirmRequest: 'Netefatsa Kopo',
        cancel: 'Khansela',
        requestSent: 'Kopo e Rometswe!',
        requestSentDesc: 'Kopo ya gago ya seshene e rometswe ka katlego.',
        close: 'Tswala',
        noTutorsFound: 'Ga go barutabana ba ba fitlhelwang mo patlisisong ya gago. Leka thuto kgotsa porofense e nngwe.',
        resourcesTitle: 'Laeborari ya go Ithuta ya Data e Nnye',
        resourcesSubtitle: 'Lebelela dipampiri tsa tlhatlhobo tsa semmuso le dikakaretso tse tswang kwa DBE le WCED.',
        downloadPDF: 'Laisa PDF (Go Dirisa Data)',
        officialSource: 'Motswedi wa Semmuso',
        hi: 'Dumela',
        mySessions: 'Diseshini tsa Me',
        noSessionsBooked: 'Ga go diseshini tse di beilweng. Bea morutabana go simolola!',
        findTutorBtn: 'Batla Morutabana',
        subjectProgress: 'Tswelelopele ya Thuto',
        progressDesc: 'Latela tswelelopele ya gago fano fa o simolola diseshini.',
        tutorLabel: 'Morutabana',
        dateLabel: 'Letlha',
        messageLabel: 'Molaetsa',
        statusLabel: 'Boemo',
        waitingTutor: 'E letetse Morutabana',
        accepted: 'E Amogetswe',
        declined: 'E Gannetswe',
        chatWhatsApp: 'Buisana ka WhatsApp',
        joinMeeting: 'Tsenela Kopano',
        howItWorks: 'E Dirwa Jang',
        howStep1Title: 'Ikwadise',
        howStep1Desc: 'Dira akhaonto ya gago ya mahala jaaka Moithuti kgotsa Morutabana ka tlase ga metsotso e 2.',
        howStep2Title: 'Batla Morutabana',
        howStep2Desc: 'Lebelela barutabana ba ba netefaditsweng ka thuto le porofense, lebelela maikutlo a bone, mme o buisane ka WhatsApp.',
        howStep3Title: 'Bea & Ithuta',
        howStep3Desc: 'Kopa seshene, e amogelwe, mme o kopane mo inthaneteng ka Zoom, Teams, kgotsa Jitsi.',
    },
    nso: {
        home: 'Gae',
        findTutor: 'Hwetša Morutiši',
        resources: 'Dithušo',
        dashboard: 'Dashboard ya Ka',
        logout: 'Tšwa',
        signUp: 'Ngwadiša',
        logIn: 'Tsena',
        selectRole: 'Kgetha karolo ya gago go tšwela pele.',
        learner: 'Moithuti',
        tutor: 'Morutiši',
        email: 'Aterese ya imeile',
        password: 'Phasewete',
        loginBtn: 'Tsena',
        noAccount: 'Ga o na akhaonto?',
        createAccount: 'Bopa akhaonto ya gago',
        chooseRole: 'Kgetha karolo ya gago go thoma.',
        iAmLearner: 'Ke Moithuti',
        iAmTutor: 'Ke Morutiši',
        fullName: 'Leina le Feletšego',
        createPassword: 'Bopa phasewete',
        currentGrade: 'Kreiti ya Bjale',
        selectGrade: 'Kgetha Kreiti',
        grade10: 'Kreiti 10',
        grade11: 'Kreiti 11',
        grade12: 'Kreiti 12 (Matric)',
        province: 'Profense',
        selectProvince: 'Kgetha Profense',
        subjectsTeach: 'Dithuto tše o ka di rutago',
        yearsExp: 'Mengwaga ya Boitsebi',
        signUpLearner: 'Ngwadiša bjalo ka Moithuti',
        signUpTutor: 'Ngwadiša bjalo ka Morutiši',
        alreadyAccount: 'O šetše o na le akhaonto?',
        unlockTitle: 'Bula Monyako wa Gago wa Yunibesithi.',
        unlockSubtitle: 'Baithuti ba ba fetago 700,000 ba ile ba swanela go ithuta yunibesithing ngwagola, eupša dikete tša batho ba ile ba ganetšwa.',
        joinWaitlist: 'Tsenela Lenaneo la go Leta',
        exploreSubjects: 'Nyakišiša Dithuto',
        beFirst: 'Ba wa pele go tseba.',
        joinDescription: 'Tsenela lenaneo la rena la go leta go hwetša phihlelelo ya pele ge re thoma.',
        enterEmail: 'Tsenya aterese ya gago ya imeile',
        thankYou: "O lenaneong!",
        subjectsMatter: 'Dithuto tše Bohlokwa',
        subjectsSubtitle: 'Go tseba tše go bula menyako ya Boenjiniere, Bongaka, Kgoebo le Molao.',
        whatBuilding: 'Se re go agelago sona',
        gatewayMastery: 'Go Tseba Dithuto tša Bohlokwa',
        gatewayMasteryDesc: 'Didirišwa tše di lebantšwego dithutong tše di thibelago monyako wa yunibesithi.',
        affordableDesign: 'E Hwetšega ka Theko ya Tlase',
        affordableDesignDesc: 'Go fokotša ditshenyegelo tše di phagameng tša R300+/iri go dira gore thušo ya thuto e hwetšagale.',
        dataLight: 'Data e Nnyane & ya Gae',
        dataLightDesc: 'E agetšwe Afrika Borwa. Tirišo e nnyane ya data, mobile pele, le thekgo ya maleme a 11.',
        findTutorTitle: 'Hwetša Morutiši wa Gago',
        searchSubject: 'Nyaka ka thuto (mohl. Dipalo)',
        allProvinces: 'Diprofense Ka Moka',
        requestSession: 'Kopa Seshene',
        preferredDate: 'Letšatši leo o le Ratago',
        preferredTime: 'Nako yeo o e Ratago',
        helpWith: 'O hloka thušo ka eng?',
        confirmRequest: 'Netefatša Kopo',
        cancel: 'Khansela',
        requestSent: 'Kopo e Rometšwe!',
        requestSentDesc: 'Kopo ya gago ya seshene e rometšwe ka katlego.',
        close: 'Tswalela',
        noTutorsFound: 'Ga go barutiši ba ba hweditšwego bakeng sa nyakišišo ya gago. Leka thuto goba profense e nngwe.',
        resourcesTitle: 'Laeborari ya go Ithuta ya Data e Nnyane',
        resourcesSubtitle: 'Lebelela dipampiri tša tlhahlobo tša semmuso le dikakaretšo tše di tšwago go DBE le WCED.',
        downloadPDF: 'Laiša PDF (Go Šomiša Data)',
        officialSource: 'Mohlodi wa Semmuso',
        hi: 'Dumela',
        mySessions: 'Diseshini tša Ka',
        noSessionsBooked: 'Ga go diseshini tše di beilwego. Bea morutiši go thoma!',
        findTutorBtn: 'Hwetša Morutiši',
        subjectProgress: 'Tšwelopele ya Thuto',
        progressDesc: 'Latela tšwelopele ya gago mo ge o thoma diseshini.',
        tutorLabel: 'Morutiši',
        dateLabel: 'Letšatši',
        messageLabel: 'Molaetša',
        statusLabel: 'Boemo',
        waitingTutor: 'E letetše Morutiši',
        accepted: 'E Amogetšwe',
        declined: 'E Ganetšwe',
        chatWhatsApp: 'Bolela ka WhatsApp',
        joinMeeting: 'Tsenela Kopano',
        howItWorks: 'E Dira Bjwang',
        howStep1Title: 'Ngwadiša',
        howStep1Desc: 'Bopa akhaonto ya gago ya mahala bjalo ka Moithuti goba Morutiši ka tlase ga metsotso e 2.',
        howStep2Title: 'Hwetša Morutiši',
        howStep2Desc: 'Lebelela barutiši ba ba netefaditšwego ka thuto le profense, lebelela maikutlo a bona, gomme o bolele ka WhatsApp.',
        howStep3Title: 'Bea & Ithuta',
        howStep3Desc: 'Kopa seshene, e amogelwe, gomme o kopane inthaneteng ka Zoom, Teams, goba Jitsi.',
    },
    ts: {
        home: 'Kaya',
        findTutor: 'Kuma Mudyondzisi',
        resources: 'Switirhisiwa',
        dashboard: 'Dashboard ya Mina',
        logout: 'Huma',
        signUp: 'Tsarisa',
        logIn: 'Nghena',
        selectRole: 'Hlawula xiphemu xa wena leswaku u ya emahlweni.',
        learner: 'Mudyondzi',
        tutor: 'Mudyondzisi',
        email: 'Adirese ya imeyili',
        password: 'Phasiwedi',
        loginBtn: 'Nghena',
        noAccount: 'A wu na akhawunti?',
        createAccount: 'Endla akhawunti ya wena',
        chooseRole: 'Hlawula xiphemu xa wena leswaku u sungula.',
        iAmLearner: 'Ndzi Mudyondzi',
        iAmTutor: 'Ndzi Mudyondzisi',
        fullName: 'Vito leri Heteleke',
        createPassword: 'Endla phasiwedi',
        currentGrade: 'Giredi ya Sweswi',
        selectGrade: 'Hlawula Giredi',
        grade10: 'Giredi 10',
        grade11: 'Giredi 11',
        grade12: 'Giredi 12 (Matric)',
        province: 'Phurovinsi',
        selectProvince: 'Hlawula Phurovinsi',
        subjectsTeach: 'Tidyondzo leti u nga ti dyondzisaka',
        yearsExp: 'Malembe ya Ntokoto',
        signUpLearner: 'Tsarisa tanihi Mudyondzi',
        signUpTutor: 'Tsarisa tanihi Mudyondzisi',
        alreadyAccount: 'U lerova u ri na akhawunti?',
        unlockTitle: 'Pfula Nyangwa wa Wena wa Yunivhesiti.',
        unlockSubtitle: 'Vadyondzi vo tlula 700,000 va fikelele xikolo xa le henhla lembe leri hundzeke, kambe magidi ya vanhu va aleriwile.',
        joinWaitlist: 'Joyina Nxaxamelo wa Ku Rindzela',
        exploreSubjects: 'Kambisisa Tidyondzo',
        beFirst: 'Va wo sungula ku tiva.',
        joinDescription: 'Joyina nxaxamelo wa hina wa ku rindzela leswaku u kuma nkhomeko wo sungula loko hi sungula.',
        enterEmail: 'Nghenisa adirese ya wena ya imeyili',
        thankYou: "U eka nxaxamelo!",
        subjectsMatter: 'Tidyondzo leti Nkoka',
        subjectsSubtitle: 'Ku tiva leti swi pfula swiyelo swa Vuinjiniyela, Vuvabyi, Vuxavisi na Nawu.',
        whatBuilding: 'Leswi hi ku akelaka swona',
        gatewayMastery: 'Ku Tiva Tidyondzo ta Nkoka',
        gatewayMasteryDesc: 'Switirhisiwa leswi kongomisiweke eka tidyondzo leti sivelaka nyangwa wa yunivhesiti.',
        affordableDesign: 'Swi Kumeleka hi Mpimo wo Hansi',
        affordableDesignDesc: 'Ku hunguta mitengo yo tshwuka ya R300+/awara leswaku nseketelo wa dyondzo wu kumeka.',
        dataLight: 'Data yitsongo & ya Kaya',
        dataLightDesc: 'Yi akeriwe Afrika Dzonga. Matirhiselo yo hansi ya data, mobile ku sungula, na nseketelo wa tindzimi ta 11.',
        findTutorTitle: 'Kuma Mudyondzisi wa Wena',
        searchSubject: 'Lava hi dyondzo (xik. Tinhlayo)',
        allProvinces: 'Maphurovinsi Hinkwawo',
        requestSession: 'Lomba Sesheni',
        preferredDate: 'Siku leri u ri Rhandzaka',
        preferredTime: 'Nkarhi lowu u wu Rhandzaka',
        helpWith: 'U lava mpfuno hi yini?',
        confirmRequest: 'Tiyisisa Xikombelo',
        cancel: 'Tshika',
        requestSent: 'Xikombelo Xi Rhumiwile!',
        requestSentDesc: 'Xikombelo xa wena xa sesheni xi rhumiwile hi ndlela leyinene.',
        close: 'Pfala',
        noTutorsFound: 'A ku na vadyondzisi lava kumekeke eka mavonelo ya wena. Ringeta dyondzo kumbe phurovinsi yin\'wana.',
        resourcesTitle: 'Layiburari yo Dyondza ya Data yitsongo',
        resourcesSubtitle: 'Languta maphepha ya mihlolo ya ximfumo na swikomiso leswi humaka eka DBE na WCED.',
        downloadPDF: 'Dawuniloda PDF (Ku Tirhisa Data)',
        officialSource: 'Xihlovo xa Ximfumo',
        hi: 'Avuxeni',
        mySessions: 'Tisesheni ta Mina',
        noSessionsBooked: 'A ku na tisesheni leti vekiweke. Veka mudyondzisi leswaku u sungula!',
        findTutorBtn: 'Kuma Mudyondzisi',
        subjectProgress: 'Nhluvuko wa Dyondzo',
        progressDesc: 'Landzelela nhluvuko wa wena laha loko u sungula tisesheni.',
        tutorLabel: 'Mudyondzisi',
        dateLabel: 'Siku',
        messageLabel: 'Marungula',
        statusLabel: 'Xiyimo',
        waitingTutor: 'Yi rindzele Mudyondzisi',
        accepted: 'Yi Amukeriwile',
        declined: 'Yi Aleriwile',
        chatWhatsApp: 'Bula hi WhatsApp',
        joinMeeting: 'Joyina Nhlangano',
        howItWorks: 'Swi Tirha Njani',
        howStep1Title: 'Tsarisa',
        howStep1Desc: 'Endla akhawunti ya wena ya mahala tanihi Mudyondzi kumbe Mudyondzisi ehansi ka timinete ta 2.',
        howStep2Title: 'Kuma Mudyondzisi',
        howStep2Desc: 'Languta vadyondzisi lava tiyisisiweke hi dyondzo na phurovinsi, languta mavonelo ya vona, naswona u bula hi WhatsApp.',
        howStep3Title: 'Veka & Dyondza',
        howStep3Desc: 'Lomba sesheni, yi amukeriwile, naswona u hlangana eka inthanete hi Zoom, Teams, kumbe Jitsi.',
    },
    ve: {
        home: 'Hayani',
        findTutor: 'Wana Mudededzi',
        resources: 'Zwishumiswa',
        dashboard: 'Dashboard Yanga',
        logout: 'Bva',
        signUp: 'Nwadisa',
        logIn: 'Dzhena',
        selectRole: 'Nanga tshipida tshau u itela u bvela phanda.',
        learner: 'Mutshudeni',
        tutor: 'Mudededzi',
        email: 'Adiresi ya imeili',
        password: 'Phasiwede',
        loginBtn: 'Dzhena',
        noAccount: 'A vha na akhaundo?',
        createAccount: 'Ita akhaundo yau',
        chooseRole: 'Nanga tshipida tshau u thoma.',
        iAmLearner: 'Ndi Mutshudeni',
        iAmTutor: 'Ndi Mudededzi',
        fullName: 'Dzina Ḽoṱhe',
        createPassword: 'Ita phasiwede',
        currentGrade: 'Gireidi ya Zwino',
        selectGrade: 'Nanga Gireidi',
        grade10: 'Gireidi 10',
        grade11: 'Gireidi 11',
        grade12: 'Gireidi 12 (Matric)',
        province: 'Vundu',
        selectProvince: 'Nanga Vundu',
        subjectsTeach: 'Zwifundo zwine wa nga zwi funza',
        yearsExp: 'Minyaka ya Tshenzhemo',
        signUpLearner: 'Nwadisa sa Mutshudeni',
        signUpTutor: 'Nwadisa sa Mudededzi',
        alreadyAccount: 'No no vha na akhaundo?',
        unlockTitle: 'Vula Mgonzo Wau wa Yunivesithi.',
        unlockSubtitle: 'Vhatshudeni vha fhiraho 700,000 vho swikela u guda yunivesithi ṅwaha wo fhelaho, fhedzi magidi a vhathu vho imiswa.',
        joinWaitlist: 'Dzhenela Muthethe wa u Lindela',
        exploreSubjects: 'Sedzulusa Zwifundo',
        beFirst: 'Vha wa u thoma u divha.',
        joinDescription: 'Dzhenela muthethe washu wa u lindela u wana u swikelela ha u thoma musi ri thoma.',
        enterEmail: 'Dzhenisa adiresi yau ya imeili',
        thankYou: "Ni kha muthethe!",
        subjectsMatter: 'Zwifundo Zwa Ndeme',
        subjectsSubtitle: 'U divha hezwi zwi vula misumo ya Vhuinjiniya, Vhulwadze, Vhubindudzi na Mulayo.',
        whatBuilding: 'Zwine ra vha fhaḓa',
        gatewayMastery: 'U Divha Zwifundo zwa Ndeme',
        gatewayMasteryDesc: 'Zwishumiswa zwine zwa sedza kha zwifundo zwine zwa thivhela mgonzo wa yunivesithi.',
        affordableDesign: 'Zwi Wanala nga Mutengo wo Fhungo',
        affordableDesignDesc: 'U fhungudza mitengo yo khetheaho ya R300+/awara u itela uri thuso ya pfunzo i wanale.',
        dataLight: 'Data Nṱuku & ya Hayani',
        dataLightDesc: 'Yo fhaḓwa Afrika Tshipembe. Kushumiswa ku ṱuku ha data, mobile u thoma, na thikhedzo ya nyambo dza 11.',
        findTutorTitle: 'Wana Mudededzi Wau',
        searchSubject: 'Ṱoḓa nga tshifundo (tsh. Mbalo)',
        allProvinces: 'Vundu Ḽoṱhe',
        requestSession: 'Humbela Sesheni',
        preferredDate: 'Ḓuvha ḽine wa ḽi Funaho',
        preferredTime: 'Tshifhinga tshine wa tshi Funaho',
        helpWith: 'Ni ṱoḓa thuso nga mini?',
        confirmRequest: 'Khwaṱhisedza Khumbelo',
        cancel: 'Khansela',
        requestSent: 'Khumbelo Yo Rumelwa!',
        requestSentDesc: 'Khumbelo yau ya sesheni yo rumelwa nga ndila yavhuḓi.',
        close: 'Vala',
        noTutorsFound: 'A hu na vhadededzi vho wanalaho kha ṱhoḓisiso yau. Linga tshifundo tshinwe kana vundu.',
        resourcesTitle: 'Layiburari ya u Guda ya Data Nṱuku',
        resourcesSubtitle: 'Sedza mabammbiri a milingo a tshiofisi na zwipfufhi zwi bvaho kha DBE na WCED.',
        downloadPDF: 'Ḓauniloda PDF (U Shumisa Data)',
        officialSource: 'Tshisima tsha Tshiofisi',
        hi: 'Ndaa',
        mySessions: 'Dzisesheni Dzaṅga',
        noSessionsBooked: 'A hu na dzisesheni dzo vhekwaho. Vhea mudededzi u thoma!',
        findTutorBtn: 'Wana Mudededzi',
        subjectProgress: 'Mvelaphanda ya Tshifundo',
        progressDesc: 'Landelela mvelaphanda yau afha musi ni thoma dzisesheni.',
        tutorLabel: 'Mudededzi',
        dateLabel: 'Ḓuvha',
        messageLabel: 'Mulaedza',
        statusLabel: 'Tshiimo',
        waitingTutor: 'I lindela Mudededzi',
        accepted: 'Yo Ṱanganelwa',
        declined: 'Yo Landulwa',
        chatWhatsApp: 'Amba nga WhatsApp',
        joinMeeting: 'Dzhenela Mutsindo',
        howItWorks: 'Zwi Shuma Hani',
        howStep1Title: 'Nwadisa',
        howStep1Desc: 'Ita akhaundo yau ya mahala sa Mutshudeni kana Mudededzi nga fhasi ha mimunithi ya 2.',
        howStep2Title: 'Wana Mudededzi',
        howStep2Desc: 'Sedza vhadededzi vho khwaṱhisedzwaho nga tshifundo na vundu, sedza mihumbulo yavho, nahone ni ambe nga WhatsApp.',
        howStep3Title: 'Vhea & Guda',
        howStep3Desc: 'Humbela sesheni, i ṱanganelwe, nahone ni ṱangane kha inthanethe nga Zoom, Teams, kana Jitsi.',
    },
    ss: {
        home: 'Ekhaya',
        findTutor: 'Tfola Umfundzisi',
        resources: 'Tinsita',
        dashboard: 'Idashboard Yami',
        logout: 'Phuma',
        signUp: 'Bhalisa',
        logIn: 'Ngena',
        selectRole: 'Khetsa indzima yakho kutsi uchubeke.',
        learner: 'Umfundzi',
        tutor: 'Umfundzisi',
        email: 'Likheli le-imeyili',
        password: 'Iphasiwedi',
        loginBtn: 'Ngena',
        noAccount: 'Awunayo i-akhawunti?',
        createAccount: 'Dala i-akhawunti yakho',
        chooseRole: 'Khetsa indzima yakho kutsi ucale.',
        iAmLearner: 'Ngiyi Umfundzi',
        iAmTutor: 'Ngiyi Umfundzisi',
        fullName: 'Ligama Leligcwele',
        createPassword: 'Dala iphasiwedi',
        currentGrade: 'Libanga Lanyalo',
        selectGrade: 'Khetsa Libanga',
        grade10: 'Libanga 10',
        grade11: 'Libanga 11',
        grade12: 'Libanga 12 (Matric)',
        province: 'Sifundza',
        selectProvince: 'Khetsa Sifundza',
        subjectsTeach: 'Tifundvo longatfundzisa tona',
        yearsExp: 'Iminyaka Yelwati',
        signUpLearner: 'Bhalisa njenge Umfundzi',
        signUpTutor: 'Bhalisa njenge Umfundzisi',
        alreadyAccount: 'Sewunayo i-akhawunti?',
        unlockTitle: 'Vula Umnyango Wakho Weyunivesithi.',
        unlockSubtitle: 'Bafundzi labangetulu kwa-700,000 bagcwalisa ticondziso letiphakeme ngemnyaka lophelile, kodwa magidzi etintsango akhishwa.',
        joinWaitlist: 'Joyina Luhlu Lwekubekela',
        exploreSubjects: 'Hlola Tifundvo',
        beFirst: 'Yiba nguwekucala kwekutsi wati.',
        joinDescription: 'Joyina luhlu lwetsu lwekubekela kutsi utfole kufinyelela kwekucala nasi secala.',
        enterEmail: 'Faka likheli lakho le-imeyili',
        thankYou: "Usoluhlu!",
        subjectsMatter: 'Tifundvo Letibalulekile',
        subjectsSubtitle: 'Kwati leti kuvula ticango teBunjhiniyela, Temitsi, Tebhizinisi neMtsetfo.',
        whatBuilding: 'Loko lesikwakhela kona',
        gatewayMastery: 'Kwati Tifundvo Letibalulekile',
        gatewayMasteryDesc: 'Tinsita letigxile etifundvweni letivimbela umnyango weyunivesithi.',
        affordableDesign: 'Kuyatfolakala Ngetintfo Letiphansi',
        affordableDesignDesc: 'Kunciphisa tindzaba letiphakeme ta-R300+/lihora kutsi lusito lwetemfundvo lutfoleke.',
        dataLight: 'Idatha Lencane & Yasekhaya',
        dataLightDesc: 'Yakhelwe iNingizimu Afrika. Kusetjentiswa lokuncane kwedatha, mobile kucala, nekwekucinisekisa tilwimi leti-11.',
        findTutorTitle: 'Tfola Umfundzisi Wakho',
        searchSubject: 'Sesha ngesifundvo (sib. Tibalobalo)',
        allProvinces: 'Tonkhe Tifundza',
        requestSession: 'Cela Seshini',
        preferredDate: 'Lilanga Lolilitsandzako',
        preferredTime: 'Sikhatsi Lositsandzako',
        helpWith: 'Udinga lusito nga ini?',
        confirmRequest: 'Cinisekisa Sicelo',
        cancel: 'Khansela',
        requestSent: 'Sicelo Sitsetfwe!',
        requestSentDesc: 'Sicelo sakho seseshini sitsetfwe ngalokuncono.',
        close: 'Vala',
        noTutorsFound: 'Kute bafundzisi labatfolakele ekusesheni kwakho. Zama lesinye sifundvo noma sifundza.',
        resourcesTitle: 'Layiburari Yekufundza Yedatha Lencane',
        resourcesSubtitle: 'Buka emaphepha emihlolo lasemtsetfweni kanye nesifinyezo lesivela ku-DBE ne-WCED.',
        downloadPDF: 'Dawuniloda i-PDF (Kusebenta Idatha)',
        officialSource: 'Umthombo Semtsetfweni',
        hi: 'Sawubona',
        mySessions: 'Tiseshini Tami',
        noSessionsBooked: 'Kute tiseshini letibhukiwe. Bhuka umfundzisi kutsi ucale!',
        findTutorBtn: 'Tfola Umfundzisi',
        subjectProgress: 'Intfutfuko Yesifundvo',
        progressDesc: 'Landzela intfutfuko yakho lapha nawucala tiseshini.',
        tutorLabel: 'Umfundzisi',
        dateLabel: 'Lilanga',
        messageLabel: 'Umlayeto',
        statusLabel: 'Simo',
        waitingTutor: 'Ilindzele Umfundzisi',
        accepted: 'Yemukelwe',
        declined: 'Yenqatshwe',
        chatWhatsApp: 'Khuluma nge-WhatsApp',
        joinMeeting: 'Joyina Umhlangano',
        howItWorks: 'Kusebenta Njani',
        howStep1Title: 'Bhalisa',
        howStep1Desc: 'Dala i-akhawunti yakho yamahhala njenge Umfundzi noma Umfundzisi ngaphansi kwemizuzu lemi-2.',
        howStep2Title: 'Tfola Umfundzisi',
        howStep2Desc: 'Buka bafundzisi labacinisekisiwe ngesifundvo nangesifundza, buka imibono yabo, bese ukhuluma nge-WhatsApp.',
        howStep3Title: 'Bhuka & Fundza',
        howStep3Desc: 'Cela seshini, yemukelwe, bese uhlangana ku-inthanethi nge-Zoom, Teams, noma i-Jitsi.',
    },
    nr: {
        home: 'Ikhaya',
        findTutor: 'Funa Umfundisi',
        resources: 'Izinsiza',
        dashboard: 'Idashboard Yami',
        logout: 'Phuma',
        signUp: 'Bhalisa',
        logIn: 'Ngena',
        selectRole: 'Khetha indima yakho ukuqhubeka.',
        learner: 'Umfundi',
        tutor: 'Umfundisi',
        email: 'Ikheli le-imeyili',
        password: 'Iphasiwedi',
        loginBtn: 'Ngena',
        noAccount: 'Awunayo i-akhawunti?',
        createAccount: 'Dala i-akhawunti yakho',
        chooseRole: 'Khetha indima yakho ukuqala.',
        iAmLearner: 'Ngi Umfundi',
        iAmTutor: 'Ngi Umfundisi',
        fullName: 'Ibizo Elipheleleko',
        createPassword: 'Dala iphasiwedi',
        currentGrade: 'Ibanga Lamanje',
        selectGrade: 'Khetha Ibanga',
        grade10: 'Ibanga 10',
        grade11: 'Ibanga 11',
        grade12: 'Ibanga 12 (Matric)',
        province: 'Iphrovinsi',
        selectProvince: 'Khetha Iphrovinsi',
        subjectsTeach: 'Iifundo ongazifundisa',
        yearsExp: 'Iminyaka Yelwazi',
        signUpLearner: 'Bhalisa njengo Mfundi',
        signUpTutor: 'Bhalisa njengo Mfundisi',
        alreadyAccount: 'Usunayo i-akhawunti?',
        unlockTitle: 'Vula Umnyango Wakho Weyunivesithi.',
        unlockSubtitle: 'Abafundi abangaphezu kwe-700,000 bagcwalisa iimfundo eziphakemeko ngomnyaka ophelileko, kodwa amagidi wabantu abikelwa.',
        joinWaitlist: 'Joyina Irhelo Lokulinda',
        exploreSubjects: 'Hlola Iimfundo',
        beFirst: 'Yiba ngowokuqala ukwazi.',
        joinDescription: 'Joyina irhelo lethu lokulinda ukuze ufumane ukufinyelela kwangaphambili nasi siqala.',
        enterEmail: 'Faka ikheli lakho le-imeyili',
        thankYou: "Usorhelweni!",
        subjectsMatter: 'Iimfundo Ezibalulekileko',
        subjectsSubtitle: 'Ukutjheja lezi kuvula iincomo zeBunjhiniyela, Ezempilo, Ezebhizinisi neZomthetho.',
        whatBuilding: 'Lokhu esikwakhela khona',
        gatewayMastery: 'Ukutjheja Iimfundo Ezibalulekileko',
        gatewayMasteryDesc: 'Iinsiza ezigxile kwiimfundo ezivimbela umnyango weyunivesithi.',
        affordableDesign: 'Kutholakala Ngeendleko Eziphasi',
        affordableDesignDesc: 'Ukunciphisa iindleko eziphakemeko zama-R300+/ihora ukuze usizo lweemfundo lutholakale.',
        dataLight: 'Idatha Encani & Yasekhaya',
        dataLightDesc: 'Yakhelwe iNingizimu Afrika. Ukusetjenziswa okuncani kwedatha, mobile kuqala, nekwekusekela iilimi ezili-11.',
        findTutorTitle: 'Funa Umfundisi Wakho',
        searchSubject: 'Rhoda ngefundo (isb. Izibalo)',
        allProvinces: 'Zoke Iiprovinsi',
        requestSession: 'Cela Iseshini',
        preferredDate: 'Ilanga Olithandako',
        preferredTime: 'Isikhathi Osithandako',
        helpWith: 'Udinga usizo ngeni?',
        confirmRequest: 'Qinisekisa Isicelo',
        cancel: 'Khansela',
        requestSent: 'Isicelo Sithunyelwe!',
        requestSentDesc: 'Isicelo sakho seseshini sithunyelwe ngendlela efaneleko.',
        close: 'Vala',
        noTutorsFound: 'Akuna bafundisi abatholakeleko ekurhodeni kwakho. Zama esinye isifundo namkha iphrovinsi.',
        resourcesTitle: 'Layiburari Yokufunda Yedatha Encani',
        resourcesSubtitle: 'Buka amaphepha wemihlolo asemthethweni kanye neesifinyezo ezivela ku-DBE ne-WCED.',
        downloadPDF: 'Dawuniloda i-PDF (Kusetjenziswa Idatha)',
        officialSource: 'Umthombo Osemthethweni',
        hi: 'Lotjha',
        mySessions: 'Iiseshini Zami',
        noSessionsBooked: 'Akuna seshini ezibhukiweko. Bhuka umfundisi ukuze uqale!',
        findTutorBtn: 'Funa Umfundisi',
        subjectProgress: 'Intuthuko Yefundo',
        progressDesc: 'Landela intuthuko yakho lapha nawuqala iiseshini.',
        tutorLabel: 'Umfundisi',
        dateLabel: 'Ilanga',
        messageLabel: 'Umlayezo',
        statusLabel: 'Isimo',
        waitingTutor: 'Ilindele Umfundisi',
        accepted: 'Yemukelwe',
        declined: 'Yenqatshwe',
        chatWhatsApp: 'Khuluma nge-WhatsApp',
        joinMeeting: 'Joyina Umhlangano',
        howItWorks: 'Isebenza Njani',
        howStep1Title: 'Bhalisa',
        howStep1Desc: 'Dala i-akhawunti yakho yamahhala njengo Mfundi namkha Umfundisi ngaphasi kwemizuzu emi-2.',
        howStep2Title: 'Funa Umfundisi',
        howStep2Desc: 'Buka abafundisi abaqinisekisiweko ngefundo nangephrovinsi, buka imibono yabo, begodu ukhuluma nge-WhatsApp.',
        howStep3Title: 'Bhuka & Funda',
        howStep3Desc: 'Cela iseshini, yemukelwe, begodu uhlangana ku-inthanethi nge-Zoom, Teams, namkha i-Jitsi.',
    },

};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: Translations;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    const value = {
        language,
        setLanguage,
        t: translations[language],
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}